<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520103307 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE notificacion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, mensaje VARCHAR(255) NOT NULL, leido BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usuario_id INT NOT NULL, viaje_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_729A19ECDB38439E ON notificacion (usuario_id)');
        $this->addSql('CREATE INDEX IDX_729A19EC94E1E648 ON notificacion (viaje_id)');
        $this->addSql('ALTER TABLE notificacion ADD CONSTRAINT FK_729A19ECDB38439E FOREIGN KEY (usuario_id) REFERENCES usuario (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notificacion ADD CONSTRAINT FK_729A19EC94E1E648 FOREIGN KEY (viaje_id) REFERENCES viaje (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE notificacion DROP CONSTRAINT FK_729A19ECDB38439E');
        $this->addSql('ALTER TABLE notificacion DROP CONSTRAINT FK_729A19EC94E1E648');
        $this->addSql('DROP TABLE notificacion');
    }
}
