<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260126114548 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE comentario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, comentario VARCHAR(255) NOT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id_usuario_id INT NOT NULL, id_viaje_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4B91E7027EB2C349 ON comentario (id_usuario_id)');
        $this->addSql('CREATE INDEX IDX_4B91E702C43A0ADD ON comentario (id_viaje_id)');
        $this->addSql('CREATE TABLE favoritos (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, id_usuario_id INT NOT NULL, id_viaje_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1E86887F7EB2C349 ON favoritos (id_usuario_id)');
        $this->addSql('CREATE INDEX IDX_1E86887FC43A0ADD ON favoritos (id_viaje_id)');
        $this->addSql('CREATE TABLE imagen (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url_path VARCHAR(255) NOT NULL, id_viaje_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8319D2B3C43A0ADD ON imagen (id_viaje_id)');
        $this->addSql('CREATE TABLE usuario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tipo VARCHAR(50) NOT NULL, nickname VARCHAR(100) NOT NULL, email VARCHAR(100) NOT NULL, contrasenia VARCHAR(50) NOT NULL, biografia VARCHAR(255) DEFAULT NULL, fecha_registro TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, url_foto_perfil VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE viaje (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titulo VARCHAR(150) NOT NULL, destino VARCHAR(150) NOT NULL, duracion INT NOT NULL, presupuesto DOUBLE PRECISION DEFAULT NULL, fecha_creacion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, contenido TEXT NOT NULL, id_usuario_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1D41ED167EB2C349 ON viaje (id_usuario_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE comentario ADD CONSTRAINT FK_4B91E7027EB2C349 FOREIGN KEY (id_usuario_id) REFERENCES usuario (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE comentario ADD CONSTRAINT FK_4B91E702C43A0ADD FOREIGN KEY (id_viaje_id) REFERENCES viaje (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE favoritos ADD CONSTRAINT FK_1E86887F7EB2C349 FOREIGN KEY (id_usuario_id) REFERENCES usuario (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE favoritos ADD CONSTRAINT FK_1E86887FC43A0ADD FOREIGN KEY (id_viaje_id) REFERENCES viaje (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE imagen ADD CONSTRAINT FK_8319D2B3C43A0ADD FOREIGN KEY (id_viaje_id) REFERENCES viaje (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE viaje ADD CONSTRAINT FK_1D41ED167EB2C349 FOREIGN KEY (id_usuario_id) REFERENCES usuario (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE comentario DROP CONSTRAINT FK_4B91E7027EB2C349');
        $this->addSql('ALTER TABLE comentario DROP CONSTRAINT FK_4B91E702C43A0ADD');
        $this->addSql('ALTER TABLE favoritos DROP CONSTRAINT FK_1E86887F7EB2C349');
        $this->addSql('ALTER TABLE favoritos DROP CONSTRAINT FK_1E86887FC43A0ADD');
        $this->addSql('ALTER TABLE imagen DROP CONSTRAINT FK_8319D2B3C43A0ADD');
        $this->addSql('ALTER TABLE viaje DROP CONSTRAINT FK_1D41ED167EB2C349');
        $this->addSql('DROP TABLE comentario');
        $this->addSql('DROP TABLE favoritos');
        $this->addSql('DROP TABLE imagen');
        $this->addSql('DROP TABLE usuario');
        $this->addSql('DROP TABLE viaje');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
